// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace ProtoDatabase
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LanguageSetting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Language
        {
            get { return __pbn__Language ?? ""; }
            set { __pbn__Language = value; }
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private string __pbn__Language;

        [global::ProtoBuf.ProtoMember(2, Name = @"option")]
        [global::System.ComponentModel.DefaultValue(LanguageOption.LangoptionNone)]
        public LanguageOption Option
        {
            get { return __pbn__Option ?? LanguageOption.LangoptionNone; }
            set { __pbn__Option = value; }
        }
        public bool ShouldSerializeOption() => __pbn__Option != null;
        public void ResetOption() => __pbn__Option = null;
        private LanguageOption? __pbn__Option;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"install_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InstallPath
        {
            get { return __pbn__InstallPath ?? ""; }
            set { __pbn__InstallPath = value; }
        }
        public bool ShouldSerializeInstallPath() => __pbn__InstallPath != null;
        public void ResetInstallPath() => __pbn__InstallPath = null;
        private string __pbn__InstallPath;

        [global::ProtoBuf.ProtoMember(2, Name = @"play_region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayRegion
        {
            get { return __pbn__PlayRegion ?? ""; }
            set { __pbn__PlayRegion = value; }
        }
        public bool ShouldSerializePlayRegion() => __pbn__PlayRegion != null;
        public void ResetPlayRegion() => __pbn__PlayRegion = null;
        private string __pbn__PlayRegion;

        [global::ProtoBuf.ProtoMember(3, Name = @"desktop_shortcut")]
        [global::System.ComponentModel.DefaultValue(ShortcutOption.ShortcutNone)]
        public ShortcutOption DesktopShortcut
        {
            get { return __pbn__DesktopShortcut ?? ShortcutOption.ShortcutNone; }
            set { __pbn__DesktopShortcut = value; }
        }
        public bool ShouldSerializeDesktopShortcut() => __pbn__DesktopShortcut != null;
        public void ResetDesktopShortcut() => __pbn__DesktopShortcut = null;
        private ShortcutOption? __pbn__DesktopShortcut;

        [global::ProtoBuf.ProtoMember(4, Name = @"startmenu_shortcut")]
        [global::System.ComponentModel.DefaultValue(ShortcutOption.ShortcutNone)]
        public ShortcutOption StartmenuShortcut
        {
            get { return __pbn__StartmenuShortcut ?? ShortcutOption.ShortcutNone; }
            set { __pbn__StartmenuShortcut = value; }
        }
        public bool ShouldSerializeStartmenuShortcut() => __pbn__StartmenuShortcut != null;
        public void ResetStartmenuShortcut() => __pbn__StartmenuShortcut = null;
        private ShortcutOption? __pbn__StartmenuShortcut;

        [global::ProtoBuf.ProtoMember(5, Name = @"language_settings")]
        [global::System.ComponentModel.DefaultValue(LanguageSettingType.LangsettingNone)]
        public LanguageSettingType LanguageSettings
        {
            get { return __pbn__LanguageSettings ?? LanguageSettingType.LangsettingNone; }
            set { __pbn__LanguageSettings = value; }
        }
        public bool ShouldSerializeLanguageSettings() => __pbn__LanguageSettings != null;
        public void ResetLanguageSettings() => __pbn__LanguageSettings = null;
        private LanguageSettingType? __pbn__LanguageSettings;

        [global::ProtoBuf.ProtoMember(6, Name = @"selected_text_language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SelectedTextLanguage
        {
            get { return __pbn__SelectedTextLanguage ?? ""; }
            set { __pbn__SelectedTextLanguage = value; }
        }
        public bool ShouldSerializeSelectedTextLanguage() => __pbn__SelectedTextLanguage != null;
        public void ResetSelectedTextLanguage() => __pbn__SelectedTextLanguage = null;
        private string __pbn__SelectedTextLanguage;

        [global::ProtoBuf.ProtoMember(7, Name = @"selected_speech_language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SelectedSpeechLanguage
        {
            get { return __pbn__SelectedSpeechLanguage ?? ""; }
            set { __pbn__SelectedSpeechLanguage = value; }
        }
        public bool ShouldSerializeSelectedSpeechLanguage() => __pbn__SelectedSpeechLanguage != null;
        public void ResetSelectedSpeechLanguage() => __pbn__SelectedSpeechLanguage = null;
        private string __pbn__SelectedSpeechLanguage;

        [global::ProtoBuf.ProtoMember(8, Name = @"languages")]
        public global::System.Collections.Generic.List<LanguageSetting> Languages { get; } = new global::System.Collections.Generic.List<LanguageSetting>();

        [global::ProtoBuf.ProtoMember(9, Name = @"gfx_override_tags")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GfxOverrideTags
        {
            get { return __pbn__GfxOverrideTags ?? ""; }
            set { __pbn__GfxOverrideTags = value; }
        }
        public bool ShouldSerializeGfxOverrideTags() => __pbn__GfxOverrideTags != null;
        public void ResetGfxOverrideTags() => __pbn__GfxOverrideTags = null;
        private string __pbn__GfxOverrideTags;

        [global::ProtoBuf.ProtoMember(10, Name = @"version_branch")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VersionBranch
        {
            get { return __pbn__VersionBranch ?? ""; }
            set { __pbn__VersionBranch = value; }
        }
        public bool ShouldSerializeVersionBranch() => __pbn__VersionBranch != null;
        public void ResetVersionBranch() => __pbn__VersionBranch = null;
        private string __pbn__VersionBranch;

        [global::ProtoBuf.ProtoMember(11, Name = @"account_country")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountCountry
        {
            get { return __pbn__AccountCountry ?? ""; }
            set { __pbn__AccountCountry = value; }
        }
        public bool ShouldSerializeAccountCountry() => __pbn__AccountCountry != null;
        public void ResetAccountCountry() => __pbn__AccountCountry = null;
        private string __pbn__AccountCountry;

        [global::ProtoBuf.ProtoMember(12, Name = @"geo_ip_country")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GeoIpCountry
        {
            get { return __pbn__GeoIpCountry ?? ""; }
            set { __pbn__GeoIpCountry = value; }
        }
        public bool ShouldSerializeGeoIpCountry() => __pbn__GeoIpCountry != null;
        public void ResetGeoIpCountry() => __pbn__GeoIpCountry = null;
        private string __pbn__GeoIpCountry;

        [global::ProtoBuf.ProtoMember(13, Name = @"game_subfolder")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GameSubfolder
        {
            get { return __pbn__GameSubfolder ?? ""; }
            set { __pbn__GameSubfolder = value; }
        }
        public bool ShouldSerializeGameSubfolder() => __pbn__GameSubfolder != null;
        public void ResetGameSubfolder() => __pbn__GameSubfolder = null;
        private string __pbn__GameSubfolder;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InstallHandshake : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"product")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Product
        {
            get { return __pbn__Product ?? ""; }
            set { __pbn__Product = value; }
        }
        public bool ShouldSerializeProduct() => __pbn__Product != null;
        public void ResetProduct() => __pbn__Product = null;
        private string __pbn__Product;

        [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uid
        {
            get { return __pbn__Uid ?? ""; }
            set { __pbn__Uid = value; }
        }
        public bool ShouldSerializeUid() => __pbn__Uid != null;
        public void ResetUid() => __pbn__Uid = null;
        private string __pbn__Uid;

        [global::ProtoBuf.ProtoMember(3, Name = @"settings")]
        public UserSettings Settings { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuildConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Region
        {
            get { return __pbn__Region ?? ""; }
            set { __pbn__Region = value; }
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private string __pbn__Region;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildConfig
        {
            get { return __pbn__buildConfig ?? ""; }
            set { __pbn__buildConfig = value; }
        }
        public bool ShouldSerializebuildConfig() => __pbn__buildConfig != null;
        public void ResetbuildConfig() => __pbn__buildConfig = null;
        private string __pbn__buildConfig;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BaseProductState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"installed")]
        public bool Installed
        {
            get { return __pbn__Installed.GetValueOrDefault(); }
            set { __pbn__Installed = value; }
        }
        public bool ShouldSerializeInstalled() => __pbn__Installed != null;
        public void ResetInstalled() => __pbn__Installed = null;
        private bool? __pbn__Installed;

        [global::ProtoBuf.ProtoMember(2, Name = @"playable")]
        public bool Playable
        {
            get { return __pbn__Playable.GetValueOrDefault(); }
            set { __pbn__Playable = value; }
        }
        public bool ShouldSerializePlayable() => __pbn__Playable != null;
        public void ResetPlayable() => __pbn__Playable = null;
        private bool? __pbn__Playable;

        [global::ProtoBuf.ProtoMember(3)]
        public bool updateComplete
        {
            get { return __pbn__updateComplete.GetValueOrDefault(); }
            set { __pbn__updateComplete = value; }
        }
        public bool ShouldSerializeupdateComplete() => __pbn__updateComplete != null;
        public void ResetupdateComplete() => __pbn__updateComplete = null;
        private bool? __pbn__updateComplete;

        [global::ProtoBuf.ProtoMember(4)]
        public bool backgroundDownloadAvailable
        {
            get { return __pbn__backgroundDownloadAvailable.GetValueOrDefault(); }
            set { __pbn__backgroundDownloadAvailable = value; }
        }
        public bool ShouldSerializebackgroundDownloadAvailable() => __pbn__backgroundDownloadAvailable != null;
        public void ResetbackgroundDownloadAvailable() => __pbn__backgroundDownloadAvailable = null;
        private bool? __pbn__backgroundDownloadAvailable;

        [global::ProtoBuf.ProtoMember(5)]
        public bool backgroundDownloadComplete
        {
            get { return __pbn__backgroundDownloadComplete.GetValueOrDefault(); }
            set { __pbn__backgroundDownloadComplete = value; }
        }
        public bool ShouldSerializebackgroundDownloadComplete() => __pbn__backgroundDownloadComplete != null;
        public void ResetbackgroundDownloadComplete() => __pbn__backgroundDownloadComplete = null;
        private bool? __pbn__backgroundDownloadComplete;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currentVersion
        {
            get { return __pbn__currentVersion ?? ""; }
            set { __pbn__currentVersion = value; }
        }
        public bool ShouldSerializecurrentVersion() => __pbn__currentVersion != null;
        public void ResetcurrentVersion() => __pbn__currentVersion = null;
        private string __pbn__currentVersion;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currentVersionStr
        {
            get { return __pbn__currentVersionStr ?? ""; }
            set { __pbn__currentVersionStr = value; }
        }
        public bool ShouldSerializecurrentVersionStr() => __pbn__currentVersionStr != null;
        public void ResetcurrentVersionStr() => __pbn__currentVersionStr = null;
        private string __pbn__currentVersionStr;

        [global::ProtoBuf.ProtoMember(8, Name = @"installedBuildConfig")]
        public global::System.Collections.Generic.List<BuildConfig> installedBuildConfigs { get; } = new global::System.Collections.Generic.List<BuildConfig>();

        [global::ProtoBuf.ProtoMember(9, Name = @"backgroundDownloadBuildConfig")]
        public global::System.Collections.Generic.List<BuildConfig> backgroundDownloadBuildConfigs { get; } = new global::System.Collections.Generic.List<BuildConfig>();

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string decryptionKey
        {
            get { return __pbn__decryptionKey ?? ""; }
            set { __pbn__decryptionKey = value; }
        }
        public bool ShouldSerializedecryptionKey() => __pbn__decryptionKey != null;
        public void ResetdecryptionKey() => __pbn__decryptionKey = null;
        private string __pbn__decryptionKey;

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<string> completedInstallActions { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BackfillProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"progress")]
        public double Progress
        {
            get { return __pbn__Progress.GetValueOrDefault(); }
            set { __pbn__Progress = value; }
        }
        public bool ShouldSerializeProgress() => __pbn__Progress != null;
        public void ResetProgress() => __pbn__Progress = null;
        private double? __pbn__Progress;

        [global::ProtoBuf.ProtoMember(2, Name = @"backgrounddownload")]
        public bool Backgrounddownload
        {
            get { return __pbn__Backgrounddownload.GetValueOrDefault(); }
            set { __pbn__Backgrounddownload = value; }
        }
        public bool ShouldSerializeBackgrounddownload() => __pbn__Backgrounddownload != null;
        public void ResetBackgrounddownload() => __pbn__Backgrounddownload = null;
        private bool? __pbn__Backgrounddownload;

        [global::ProtoBuf.ProtoMember(3, Name = @"paused")]
        public bool Paused
        {
            get { return __pbn__Paused.GetValueOrDefault(); }
            set { __pbn__Paused = value; }
        }
        public bool ShouldSerializePaused() => __pbn__Paused != null;
        public void ResetPaused() => __pbn__Paused = null;
        private bool? __pbn__Paused;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong downloadLimit
        {
            get { return __pbn__downloadLimit.GetValueOrDefault(); }
            set { __pbn__downloadLimit = value; }
        }
        public bool ShouldSerializedownloadLimit() => __pbn__downloadLimit != null;
        public void ResetdownloadLimit() => __pbn__downloadLimit = null;
        private ulong? __pbn__downloadLimit;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RepairProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"progress")]
        public double Progress
        {
            get { return __pbn__Progress.GetValueOrDefault(); }
            set { __pbn__Progress = value; }
        }
        public bool ShouldSerializeProgress() => __pbn__Progress != null;
        public void ResetProgress() => __pbn__Progress = null;
        private double? __pbn__Progress;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string lastDiscSetUsed
        {
            get { return __pbn__lastDiscSetUsed ?? ""; }
            set { __pbn__lastDiscSetUsed = value; }
        }
        public bool ShouldSerializelastDiscSetUsed() => __pbn__lastDiscSetUsed != null;
        public void ResetlastDiscSetUsed() => __pbn__lastDiscSetUsed = null;
        private string __pbn__lastDiscSetUsed;

        [global::ProtoBuf.ProtoMember(2, Name = @"progress")]
        public double Progress
        {
            get { return __pbn__Progress.GetValueOrDefault(); }
            set { __pbn__Progress = value; }
        }
        public bool ShouldSerializeProgress() => __pbn__Progress != null;
        public void ResetProgress() => __pbn__Progress = null;
        private double? __pbn__Progress;

        [global::ProtoBuf.ProtoMember(3)]
        public bool discIgnored
        {
            get { return __pbn__discIgnored.GetValueOrDefault(); }
            set { __pbn__discIgnored = value; }
        }
        public bool ShouldSerializediscIgnored() => __pbn__discIgnored != null;
        public void ResetdiscIgnored() => __pbn__discIgnored = null;
        private bool? __pbn__discIgnored;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0)]
        public ulong totalToDownload
        {
            get { return __pbn__totalToDownload ?? 0; }
            set { __pbn__totalToDownload = value; }
        }
        public bool ShouldSerializetotalToDownload() => __pbn__totalToDownload != null;
        public void ResettotalToDownload() => __pbn__totalToDownload = null;
        private ulong? __pbn__totalToDownload;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(0)]
        public ulong downloadRemaining
        {
            get { return __pbn__downloadRemaining ?? 0; }
            set { __pbn__downloadRemaining = value; }
        }
        public bool ShouldSerializedownloadRemaining() => __pbn__downloadRemaining != null;
        public void ResetdownloadRemaining() => __pbn__downloadRemaining = null;
        private ulong? __pbn__downloadRemaining;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CachedProductState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public BaseProductState baseProductState { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BackfillProgress backfillProgress { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RepairProgress repairProgress { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public UpdateProgress updateProgress { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProductOperations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Operation.OpNone)]
        public Operation activeOperation
        {
            get { return __pbn__activeOperation ?? Operation.OpNone; }
            set { __pbn__activeOperation = value; }
        }
        public bool ShouldSerializeactiveOperation() => __pbn__activeOperation != null;
        public void ResetactiveOperation() => __pbn__activeOperation = null;
        private Operation? __pbn__activeOperation;

        [global::ProtoBuf.ProtoMember(2, Name = @"priority")]
        public ulong Priority
        {
            get { return __pbn__Priority.GetValueOrDefault(); }
            set { __pbn__Priority = value; }
        }
        public bool ShouldSerializePriority() => __pbn__Priority != null;
        public void ResetPriority() => __pbn__Priority = null;
        private ulong? __pbn__Priority;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProductInstall : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uid
        {
            get { return __pbn__Uid ?? ""; }
            set { __pbn__Uid = value; }
        }
        public bool ShouldSerializeUid() => __pbn__Uid != null;
        public void ResetUid() => __pbn__Uid = null;
        private string __pbn__Uid;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string productCode
        {
            get { return __pbn__productCode ?? ""; }
            set { __pbn__productCode = value; }
        }
        public bool ShouldSerializeproductCode() => __pbn__productCode != null;
        public void ResetproductCode() => __pbn__productCode = null;
        private string __pbn__productCode;

        [global::ProtoBuf.ProtoMember(3, Name = @"settings")]
        public UserSettings Settings { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public CachedProductState cachedProductState { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ProductOperations productOperations { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string productFamily
        {
            get { return __pbn__productFamily ?? ""; }
            set { __pbn__productFamily = value; }
        }
        public bool ShouldSerializeproductFamily() => __pbn__productFamily != null;
        public void ResetproductFamily() => __pbn__productFamily = null;
        private string __pbn__productFamily;

        [global::ProtoBuf.ProtoMember(7, Name = @"hidden")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Hidden
        {
            get { return __pbn__Hidden ?? false; }
            set { __pbn__Hidden = value; }
        }
        public bool ShouldSerializeHidden() => __pbn__Hidden != null;
        public void ResetHidden() => __pbn__Hidden = null;
        private bool? __pbn__Hidden;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProductConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string productCode
        {
            get { return __pbn__productCode ?? ""; }
            set { __pbn__productCode = value; }
        }
        public bool ShouldSerializeproductCode() => __pbn__productCode != null;
        public void ResetproductCode() => __pbn__productCode = null;
        private string __pbn__productCode;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string metadataHash
        {
            get { return __pbn__metadataHash ?? ""; }
            set { __pbn__metadataHash = value; }
        }
        public bool ShouldSerializemetadataHash() => __pbn__metadataHash != null;
        public void ResetmetadataHash() => __pbn__metadataHash = null;
        private string __pbn__metadataHash;

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Timestamp
        {
            get { return __pbn__Timestamp ?? ""; }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private string __pbn__Timestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActiveProcess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string processName
        {
            get { return __pbn__processName ?? ""; }
            set { __pbn__processName = value; }
        }
        public bool ShouldSerializeprocessName() => __pbn__processName != null;
        public void ResetprocessName() => __pbn__processName = null;
        private string __pbn__processName;

        [global::ProtoBuf.ProtoMember(2, Name = @"pid")]
        public int Pid
        {
            get { return __pbn__Pid.GetValueOrDefault(); }
            set { __pbn__Pid = value; }
        }
        public bool ShouldSerializePid() => __pbn__Pid != null;
        public void ResetPid() => __pbn__Pid = null;
        private int? __pbn__Pid;

        [global::ProtoBuf.ProtoMember(3, Name = @"uri")]
        public global::System.Collections.Generic.List<string> Uris { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DownloadSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int downloadLimit
        {
            get { return __pbn__downloadLimit ?? -1; }
            set { __pbn__downloadLimit = value; }
        }
        public bool ShouldSerializedownloadLimit() => __pbn__downloadLimit != null;
        public void ResetdownloadLimit() => __pbn__downloadLimit = null;
        private int? __pbn__downloadLimit;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int backfillLimit
        {
            get { return __pbn__backfillLimit ?? -1; }
            set { __pbn__backfillLimit = value; }
        }
        public bool ShouldSerializebackfillLimit() => __pbn__backfillLimit != null;
        public void ResetbackfillLimit() => __pbn__backfillLimit = null;
        private int? __pbn__backfillLimit;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Database : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"productInstall")]
        public global::System.Collections.Generic.List<ProductInstall> productInstalls { get; } = new global::System.Collections.Generic.List<ProductInstall>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<InstallHandshake> activeInstalls { get; } = new global::System.Collections.Generic.List<InstallHandshake>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ActiveProcess> activeProcesses { get; } = new global::System.Collections.Generic.List<ActiveProcess>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<ProductConfig> productConfigs { get; } = new global::System.Collections.Generic.List<ProductConfig>();

        [global::ProtoBuf.ProtoMember(5)]
        public DownloadSettings downloadSettings { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong versionSummarySeqn
        {
            get { return __pbn__versionSummarySeqn.GetValueOrDefault(); }
            set { __pbn__versionSummarySeqn = value; }
        }
        public bool ShouldSerializeversionSummarySeqn() => __pbn__versionSummarySeqn != null;
        public void ResetversionSummarySeqn() => __pbn__versionSummarySeqn = null;
        private ulong? __pbn__versionSummarySeqn;

        [global::ProtoBuf.ProtoMember(7, Name = @"priorityUidList")]
        public global::System.Collections.Generic.List<string> priorityUidLists { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum LanguageOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_NONE")]
        LangoptionNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_TEXT")]
        LangoptionText = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_SPEECH")]
        LangoptionSpeech = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGOPTION_TEXT_AND_SPEECH")]
        LangoptionTextAndSpeech = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LanguageSettingType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_NONE")]
        LangsettingNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_SINGLE")]
        LangsettingSingle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_SIMPLE")]
        LangsettingSimple = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGSETTING_ADVANCED")]
        LangsettingAdvanced = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ShortcutOption
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SHORTCUT_NONE")]
        ShortcutNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SHORTCUT_USER")]
        ShortcutUser = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SHORTCUT_ALL_USERS")]
        ShortcutAllUsers = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Operation
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OP_NONE")]
        OpNone = -1,
        [global::ProtoBuf.ProtoEnum(Name = @"OP_UPDATE")]
        OpUpdate = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"OP_BACKFILL")]
        OpBackfill = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"OP_REPAIR")]
        OpRepair = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"OP_UNINSTALL")]
        OpUninstall = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
